package pojos;
// Generated Jun 5, 2018 6:48:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name="tag"
    ,catalog="konyvtar"
)
public class Tag  implements java.io.Serializable {


     private Integer id;
     private String nev;
     private String emaill;
     private Set<Konyv> konyvs = new HashSet<Konyv>(0);

    public Tag() {
    }

    public Tag(String nev, String emaill, Set<Konyv> konyvs) {
       this.nev = nev;
       this.emaill = emaill;
       this.konyvs = konyvs;
    }
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
     @Column(name="nev", length=45)
    public String getNev() {
        return this.nev;
    }
    
    public void setNev(String nev) {
        this.nev = nev;
    }
     @Column(name="emaill", length=45)
    public String getEmaill() {
        return this.emaill;
    }
    
    public void setEmaill(String emaill) {
        this.emaill = emaill;
    }
    @OneToMany(fetch=FetchType.EAGER, mappedBy="tag")
    public Set<Konyv> getKonyvs() {
        return this.konyvs;
    }
    
    public void setKonyvs(Set<Konyv> konyvs) {
        this.konyvs = konyvs;
    }




}


